KitTimeline('part2_perc5').presetCompileStringSavePath = "ex3/part2_data/kitTimeline_part2_perc5.scd";

KitTimeline('part2_perc5').eventList = XEventList.newFrom([
	(\absTime: 0, \dur: 0.0, \label: 'start', \playDur: 0.0, \relDur: 0.0, \sustain: 0, \type: 'start', ),
	(\absTime: 0.0, \dur: 0.25, \kitIndex: 0.0, \midinote: 0, \playDur: 0.25, \relDur: 0.25, \sustain: 0.1, ),
	(\absTime: 0.25, \dur: 0.75, \kitIndex: 0.0, \midinote: 0, \playDur: 0.75, \relDur: 0.75, \sustain: 0.125, ),
	(\absTime: 1.0, \dur: 1.0, \kitIndex: 4.0, \midinote: 0, \playDur: 1.0, \relDur: 1.0, \sustain: 0.1, ),
	(\absTime: 2.0, \dur: 0, \label: 'end', \playDur: 0, \relDur: 0, \type: 'end', ),
]);