NoteTimeline('part2_bass0').presetCompileStringSavePath = "ex3/part2_data/noteTimeline_part2_bass0.scd";

NoteTimeline('part2_bass0').eventList = XEventList.newFrom([
	(\absTime: 0, \dur: 0.0, \label: 'start', \playDur: 0.0, \relDur: 0.0, \sustain: 0, \type: 'start', ),
	(\absTime: 0.0, \dur: 1.75, \midinote: 40.0, \playDur: 1.75, \relDur: 1.75, \sustain: 0.375, ),
	(\absTime: 1.75, \dur: 0.25, \midinote: 36.0, \playDur: 0.25, \relDur: 0.25, \sustain: 0.25, ),
	(\absTime: 2.0, \dur: 0, \label: 'end', \playDur: 0, \relDur: 0, \type: 'end', ),
]);