TrackDef('testproj5_mixerPresetGrid').childAt(0,0).snapshot = "TrackDef('testproj5_mainTrackGrid').childAt(0,0).play;
TrackDef('testproj5_mainTrackGrid').childAt(1).stop;
TrackDef('testproj5_mainTrackGrid').childAt(2).stop;
TrackDef('testproj5_mainTrackGrid').childAt(3).stop;
TrackDef('testproj5_mainTrackGrid').childAt(4).stop;
TrackDef('testproj5_mainTrackGrid').childAt(5).stop;
TrackDef('testproj5_mainTrackGrid').childAt(6).stop;
TrackDef('testproj5_mainTrackGrid').childAt(7).stop;
TrackDef('testproj5_mainTrackGrid').childAt(8).stop;";