TrackDef('cave38rec').childAt(3, 0).score = NoteTimeline('cave38rec.3.0score');


NoteTimeline('cave38rec.3.0score').param = Param(Pdef('NoteTimelineTrack.3.instr'), 'midinote');
NoteTimeline('cave38rec.3.0score').eventList = TimelineEventList.newFrom([
	(\absTime: 0, \dur: 8, \label: 'start', \playDur: 8, \relDur: 8, \sustain: 0, \type: 'start', ),
	(\absTime: 8, \dur: 0, \label: 'end', \playDur: 0, \relDur: 0, \type: 'end', ),
]);