TrackDef('cave38rec').childAt(1, 0).score = SampleTimeline('cave38rec.1.0score');


SampleTimeline('cave38rec.1.0score').eventList = TimelineEventList.newFrom([
	(\absTime: 0, \dur: 4.0, \label: 'start', \playDur: 4.0, \relDur: 4.0, \sustain: 0, \type: 'start', ),
	(\absTime: 4.0, \dur: 0, \label: 'end', \playDur: 0, \relDur: 0, \type: 'end', ),
]);
SampleTimeline('cave38rec.1.0score').buffer = BufDef('cliprec/rec_cave38rec.1.0score_220412_175920.wav');