TrackDef('cave52').childAt(2, 0).score = SampleTimeline('cave52.2.0score');


SampleTimeline('cave52.2.0score').eventList = TimelineEventList.newFrom([
	(\absTime: 0, \dur: 178.0, \label: 'start', \playDur: 178.0, \relDur: 178.0, \sustain: 0, \type: 'start', ),
	(\absTime: 178.0, \dur: 0, \label: 'end', \playDur: 0, \relDur: 0, \type: 'end', ),
]);
SampleTimeline('cave52.2.0score').buffer = BufDef('/tmp/rec_cave52.2.0score_221126_161844.wav');